# Generated by Django 4.1.7 on 2023-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(help_text='Unique ID for feedback', primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=1000)),
                ('feedback_post', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['person_name', 'feedback_post'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.UUIDField(help_text='Unique ID for location', primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=1000)),
                ('living_cost', models.IntegerField()),
                ('weather', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['location_name', 'living_cost', 'weather'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.UUIDField(help_text='Unique ID for university', primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=1000)),
                ('university_type', models.CharField(max_length=200)),
                ('university_rank', models.IntegerField()),
                ('university_location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['university_name', 'university_type', 'university_rank', 'university_location'],
            },
        ),
    ]
