# Generated by Django 4.1.7 on 2023-02-28 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for student', primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=1000)),
                ('student_gpa', models.FloatField()),
            ],
            options={
                'ordering': ['student_name', 'student_gpa'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['feedback_post']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['university_name', 'university_type', 'university_rank', 'university_location', 'university_link']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='person_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='university_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.university'),
        ),
        migrations.AddField(
            model_name='university',
            name='university_link',
            field=models.CharField(default='http://csrankings.com', max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for feedback', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='living_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for location', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for university', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.location'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for professor', primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=1000)),
                ('professor_email', models.CharField(max_length=200)),
                ('university_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.university')),
            ],
            options={
                'ordering': ['professor_name', 'professor_email'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.student'),
        ),
    ]
