# Generated by Django 4.1.7 on 2023-03-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_student_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_pic',
            field=models.CharField(default='https://www.cs.cmu.edu/sites/default/files/styles/medium/public/2019-09/CMU-Logo-Stacked-Color-300dpi.jpg?itok=8ZQ8Z8ZJ', max_length=1000),
        ),
    ]
